spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie


