server:
  port: 8072

#spring:
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/crm-system-realm
#  cloud:
#    gateway:
#      routes:
#        - id: auth-route
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#          filters:
#            - RemoveRequestHeader= Cookie,Set-Cookie




eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


