server:
  port: 8072

  #spring:
  #  security:
  #    oauth2:
  #      resource-server:
  #        jwt:
  #          issuer-uri: http://localhost:8080/realms/crm-system-realm
  #  cloud:
  #    gateway:
  #      routes:
  #        - id: auth-route
  #          uri: lb://auth-service
  #          predicates:
  #            - Path=/auth/**
  #          filters:
  #            - RemoveRequestHeader= Cookie,Set-Cookie


  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: file-storage
          uri: lb://file-storage
          predicates:
            - Path=/filestorage/**
          filters:
            - RewritePath=/filestorage/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/company/**
          filters:
            - RewritePath=/company/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
            - AddRequestHeader=Access-Control-Allow-Origin,http://localhost:5173
            - AddRequestHeader=Access-Control-Allow-Methods,GET,POST,PUT,DELETE
            - AddRequestHeader=Access-Control-Allow-Headers,*

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


