spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm%2Fapi
    username: postgres
    password: lhs22LI=D=
    driver-class-name: org.postgresql.Driver
secret_key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

  api-docs.path: /api-docs
server:
  port: 8080